# Generated by Django 3.0.6 on 2020-06-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_populate_colors'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('email', 'car')},
        ),
    ]
